### ISSUE TITLE
Auto logout when token get expired

### ISSUE THREAD

**Issue by nati** [cloudwan/gohan_webui#11]
Auto logout when token get expired

**Comment by thayashi** [comment]
Auto logout might be a little bit dangerous and sometimes not user friendly way, so I decided to show message when token is expired. Please confirm the attached image.
This is implemented at:
https://github.com/cloudwan/gohan_webui/commit/d1f69236d77caadd55d28b1bbc7abd706d94b961
![token](https://cloud.githubusercontent.com/assets/315275/17080021/6b24fed0-50d6-11e6-87ed-03f84ee5fb0d.png)
