### ISSUE TITLE
Support Grouping for sidebar

### ISSUE THREAD

**Issue by nati** [cloudwan/gohan_webui#322]
# Problem statement

When a Gohan schema has a lot of resources, sidebar menu may contain so many items and this makes hard to find target item. 

# Proposed UI change

Grouping sidebars using serviceGroup property on sidebar definition or Gohan schema metadata. 
Add service selector button on the header. We will show only selected sidebar items with the same serviceGroup defined in the routes.

# Configuration change

add "serviceGroup" in the configuration. Service group configuration object contrail a hash object where a key is ID and value should contain metadata for the group. Currently, only title property would be used. 

```
{
    "authUrl": "http://__HOST__:9091/v2.0",
    "gohan": {
        "schema": "/gohan/v0.1/schemas",
        "url": "http://__HOST__:9091"
    },
    "sidebar": [
        {
            "path": "",
            "title": "cat",
            "serviceGroup": "manmal"
        }
    ],
    "serviceGroup": {
        "manmal": {
           "title": "Manmal"
        },
        "fish": {
           "title": "Fish"
        },
    },
}
```

# Implementation update

## app/components/Navbar  

  Add service selector using the serviceGroup configuration.  We will pick up the first item from sidebar Item for each group.

## app/components/sidebar

  filter menuItem by current serviceGroup in the current route.

**Comment by stepek** [comment]
Nice feature, let's do this!

**Comment by sealionkat** [comment]
Feature is ready :slightly_smiling_face:
